openapi: 3.0.3
info:
  title: Nordigen Account Information Services API
  version: '1.7'
paths:
  /api/accounts/{id}/:
    get:
      operationId: retrieve account metadata
      description: |-
        Access account metadata.

        Information about the account record, such as the processing status and IBAN.

        Account status is recalculated based on the error count in the latest req.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
            description: A UUID string identifying this account.
          required: true
      tags:
        - accounts
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: sample account metadata
  /api/accounts/{id}/balances/:
    get:
      operationId: retrieve account balances
      description: |-
        Access account balances.

        Balances will be returned in Berlin Group PSD2 format.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
            description: A UUID string identifying this account.
          required: true
      tags:
        - accounts
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          description: sample account balances
          content:
            application/json:
              schema:
                type: string
              examples:
                - balances:
                    - balanceAmount:
                        amount: '-961.21'
                        currency: string
                      balanceType: string
                      referenceDate: '2021-10-08'
                    - balanceAmount:
                        amount: '726.17'
                        currency: string
                      balanceType: string
                      referenceDate: '2021-10-11'
  /api/accounts/{id}/details/:
    get:
      operationId: retrieve account details
      description: |-
        Access account details.

        Account details will be returned in Berlin Group PSD2 format.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
            description: A UUID string identifying this account.
          required: true
      tags:
        - accounts
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          description: sample account details
          content:
            application/json:
              schema:
                type: string
              examples:
                - account:
                    resourceId: string
                    iban: string
                    currency: string
                    ownerName: string
                    name: string
                    product: string
                    cashAccountType: string
  /api/accounts/{id}/transactions/:
    get:
      operationId: retrieve account transactions
      description: |-
        Access account transactions.

        Transactions will be returned in Berlin Group PSD2 format.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
            description: A UUID string identifying this account.
          required: true
      tags:
        - accounts
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          description: sample transaction data
          content:
            application/json:
              schema:
                type: string
              examples:
                - transactions:
                    booked:
                      - transactionId: string
                        debtorName: string
                        debtorAccount:
                          iban: string
                        transactionAmount:
                          currency: string
                          amount: '-580.12'
                        bankTransactionCode: string
                        bookingDate: '2021-10-10T21:34:47.261597'
                        valueDate: '2021-10-13T21:34:47.274129'
                        remittanceInformationUnstructured: string
                      - transactionId: string
                        transactionAmount:
                          currency: string
                          amount: '843.32'
                        bankTransactionCode: string
                        bookingDate: '2021-10-08T21:34:47.274239'
                        valueDate: '2021-10-08T21:34:47.274253'
                        remittanceInformationUnstructured: string
                    pending:
                      - transactionAmount:
                          currency: string
                          amount: '101.52'
                        valueDate: '2021-10-12T21:34:47.274276'
                        remittanceInformationUnstructured: string
        '409':
          description: Account state does not support this operation
  /api/agreements/enduser/:
    get:
      operationId: retrieve all EUAs for an end user
      description: API endpoints related to end-user agreements.
      parameters:
        - in: query
          name: enduser_id
          schema:
            type: string
          description: Your enduser ID, used for filtering results.
          required: true
        - name: limit
          required: false
          in: query
          description: Number of results to return per page.
          schema:
            type: integer
        - name: offset
          required: false
          in: query
          description: The initial index from which to return the results.
          schema:
            type: integer
      tags:
        - agreements
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedEndUserAgreementList'
          description: ''
    post:
      operationId: create EUA
      description: API endpoints related to end-user agreements.
      tags:
        - agreements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndUserAgreement'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EndUserAgreement'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EndUserAgreement'
        required: true
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndUserAgreement'
          description: ''
  /api/agreements/enduser/{id}/:
    get:
      operationId: retrieve EUA by id
      description: API endpoints related to end-user agreements.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this end user agreement.
          required: true
      tags:
        - agreements
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndUserAgreement'
          description: EUA
    delete:
      operationId: delete EUA by id
      description: Delete End User Agreement.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this end user agreement.
          required: true
      tags:
        - agreements
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/agreements/enduser/{id}/accept/:
    put:
      operationId: accept EUA
      description: Accept an end-user agreement via the API.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this end user agreement.
          required: true
      tags:
        - agreements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnduserAcceptanceDetails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EnduserAcceptanceDetails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EnduserAcceptanceDetails'
        required: true
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndUserAgreement'
          description: EUA
  /api/agreements/enduser/{id}/text/:
    get:
      operationId: retrieve EUA text
      description: Show the text of the end-user agreement.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this end user agreement.
          required: true
      tags:
        - agreements
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          description: EUA Text
          content:
            application/json:
              schema:
                type: string
              examples:
                - en:
                    text: string
  /api/aspsps/:
    get:
      operationId: retrieve all supported ASPSP(s) in a given country
      description: List all ASPSPs available.
      parameters:
        - in: query
          name: country
          schema:
            type: string
          description: ISO 3166 two-character country code
          required: true
          examples:
            Germany:
              value: DE
              summary: Germany
              description: ISO 3166 two-character code for Germany
            UnitedKingdom:
              value: GB
              summary: United Kingdom
              description: ISO 3166 two-character code for the UK
      tags:
        - aspsps
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aspsp'
              examples:
                SomeOfSupportedASPSPs:
                  value:
                    - id: N26_NTSBDEB1
                      name: N26 Bank
                      bic: NTSBDEB1
                      transaction_total_days: '90'
                      countries:
                        - 'NO'
                        - DE
                        - '...'
                        - AT
                      logo: https://cdn.nordigen.com/ais/N26_SANDBOX_NTSBDEB1.png
                    - id: ABNAMRO_FTSBDEFAXXX
                      name: ABN AMRO Bank Commercial
                      bic: FTSBDEFAXXX
                      transaction_total_days: '558'
                      countries:
                        - DE
                      logo: https://cdn.nordigen.com/ais/ABNAMRO_FTSBDEFAXXX.png
                  summary: some of supported ASPSPs
          description: list of supported ASPSPs in the country
  /api/aspsps/{id}/:
    get:
      operationId: retrieve details about specific ASPSP
      description: Get details about a specific ASPSP.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          examples:
            N26:
              value: N26_NTSBDEB1
              summary: N26
              description: Nordigen's ASPSP ID for N26
      tags:
        - aspsps
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aspsp'
              examples:
                N26Bank:
                  value:
                    id: N26_NTSBDEB1
                    name: N26 Bank
                    bic: NTSBDEB1
                    transaction_total_days: '90'
                    countries:
                      - 'NO'
                      - DE
                      - '...'
                      - AT
                    logo: https://cdn.nordigen.com/ais/N26_SANDBOX_NTSBDEB1.png
                  summary: N26 Bank
                  description: N26 Bank
                ABNAMROBank:
                  value:
                    id: ABNAMRO_FTSBDEFAXXX
                    name: ABN AMRO Bank Commercial
                    bic: FTSBDEFAXXX
                    transaction_total_days: '558'
                    countries:
                      - DE
                    logo: https://cdn.nordigen.com/ais/ABNAMRO_FTSBDEFAXXX.png
                  summary: ABN AMRO Bank
                  description: ABN AMRO Bank
          description: ASPSP Representation
  /api/requisitions/:
    get:
      operationId: retrieve all requisitions
      description: API endpoints related to requisitions.
      parameters:
        - name: limit
          required: false
          in: query
          description: Number of results to return per page.
          schema:
            type: integer
        - name: offset
          required: false
          in: query
          description: The initial index from which to return the results.
          schema:
            type: integer
      tags:
        - requisitions
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRequisitionList'
          description: ''
    post:
      operationId: create a new requisition
      description: API endpoints related to requisitions.
      tags:
        - requisitions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Requisition'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Requisition'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Requisition'
        required: true
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Requisition'
          description: requisition
  /api/requisitions/{id}/:
    get:
      operationId: requisition by id
      description: API endpoints related to requisitions.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this requisition.
          required: true
      tags:
        - requisitions
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Requisition'
          description: requisition
    delete:
      operationId: delete requisition
      description: Delete Requisition and all End User Agreements.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this requisition.
          required: true
      tags:
        - requisitions
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/requisitions/{id}/links/:
    post:
      operationId: create ASPSP authorization link
      description: Get links for user redirection.
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this requisition.
          required: true
      tags:
        - requisitions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequisitionLinkParams'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RequisitionLinkParams'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RequisitionLinkParams'
        required: true
      security:
        - tokenAuth: []
        - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequisitionLinks'
          description: link to initiate authorization with ASPSP
components:
  schemas:
    Account:
      type: object
      description: The representation of a bank account.
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: The ID of this Account, used to refer to this account in other
            API calls.
          title: Account ID
        created:
          type: string
          format: date-time
          readOnly: true
          title: Created date/time
          description: The date & time at which the account object was created.
        last_accessed:
          type: string
          format: date-time
          nullable: true
          readOnly: true
          title: Last accessed date/time
          description: The date & time at which the account object was last accessed.
        iban:
          type: string
          readOnly: true
          description: The Account IBAN
        aspsp_identifier:
          type: string
          readOnly: true
          title: ASPSP ID
          description: The ASPSP associated with this account.
        status:
          allOf:
            - $ref: '#/components/schemas/AccountStatusEnum'
          readOnly: true
          title: Account Status
          description: The processing status of this account.
      required:
        - aspsp_identifier
        - created
        - iban
        - id
        - last_accessed
        - status
    AccountStatusEnum:
      enum:
        - DISCOVERED
        - PROCESSING
        - READY
        - ERROR
        - SUSPENDED
      type: string
    Aspsp:
      type: object
      description: Represents an ASPSP.
      properties:
        id:
          type: string
        name:
          type: string
        bic:
          type: string
        transaction_total_days:
          type: string
          default: '90'
        countries:
          type: array
          items:
            type: string
        logo:
          type: string
      required:
        - countries
        - id
        - logo
        - name
    EndUserAgreement:
      type: object
      description: Represents an end-user agreement.
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          title: End User Agreement ID
          description: The ID of this End User Agreement, used to refer to this end
            user agreement in other API calls.
        created:
          type: string
          format: date-time
          readOnly: true
          title: Created Date
          description: The date & time at which the end user agreement was created.
        max_historical_days:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          default: 90
          title: Maximum Historical Days
          description: Maximum number of days of transaction data to retrieve.
        access_valid_for_days:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          readOnly: true
          default: 90
          title: Access Valid For (Days)
          description: Number of days from acceptance that the access can be used.
        access_scope:
          type: array
          items:
            type: string
            default:
              - balances
              - details
              - transactions
            title: Level of information to access (by default all)
          default:
            - balances
            - details
            - transactions
          title: Level of information to access (by default all)
          description: Array containing one or several values of ['balances', 'details',
            'transactions']
        accepted:
          type: string
          format: date-time
          nullable: true
          readOnly: true
          title: Accepted Date
          description: The date & time at which the end user accepted the agreement.
        enduser_id:
          type: string
          nullable: true
          title: End User ID
          description: A unique ID that identifies this user in your system. For data
            protection purposes, it must be possible to identify your users using
            this value. Data protection related requests may quote this value to identify
            data subjects.
          maxLength: 256
        aspsp_id:
          type: string
          description: an ASPSP ID for this EUA
      required:
        - accepted
        - access_valid_for_days
        - aspsp_id
        - created
        - enduser_id
        - id
    EnduserAcceptanceDetails:
      type: object
      description: Represents end-user details.
      properties:
        user_agent:
          type: string
          title: user agent string for the end user
        ip_address:
          type: string
          title: end user IP address
      required:
        - ip_address
        - user_agent
    PaginatedEndUserAgreementList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/EndUserAgreement'
    PaginatedRequisitionList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Requisition'
    Requisition:
      type: object
      description: RequisitionSerializer.
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        created:
          type: string
          format: date-time
          nullable: true
          readOnly: true
          title: Created Date
          description: The date & time at which the requisition was created.
        redirect:
          type: string
          format: uri
          nullable: true
          description: redirect URL to your application after end-user authorization
            with ASPSP
        status:
          allOf:
            - $ref: '#/components/schemas/RequisitionStatusEnum'
          readOnly: true
          description: status of this requisition
        agreements:
          type: array
          items:
            type: string
            format: uuid
            title: agreements
          description: array of EUAs associated with this requisition
        accounts:
          type: array
          items:
            type: string
            format: uuid
            title: accounts
          readOnly: true
          description: array of account IDs retrieved within a scope of this requisition
        reference:
          type: string
          description: additional ID to identify the end user
          maxLength: 256
        enduser_id:
          type: string
          title: end user id
          description: end-user id in client's system, usually a UUID
          maxLength: 256
        user_language:
          type: string
          description: user language for the views
          maxLength: 5
      required:
        - accounts
        - created
        - enduser_id
        - id
        - redirect
        - reference
        - status
    RequisitionLinkParams:
      type: object
      description: RequisitionLinkParamsSerializer.
      properties:
        aspsp_id:
          type: string
          description: ASPSP ID. Should match one used while creating EUA, if it's
            linked to this requisition
      required:
        - aspsp_id
    RequisitionLinks:
      type: object
      description: RequisitionLinksSerializer.
      properties:
        initiate:
          type: string
          format: uri
          readOnly: true
      required:
        - initiate
    RequisitionStatusEnum:
      enum:
        - CR
        - ID
        - LN
        - RJ
        - ER
        - SU
        - EX
      type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
