openapi: 3.0.3
info:
  title: Nordigen Account Information Services API
  version: "1.7"
servers:
- url: /
paths:
  /api/accounts/{id}/:
    get:
      description: |-
        Access account metadata.

        Information about the account record, such as the processing status and IBAN.

        Account status is recalculated based on the error count in the latest req.
      operationId: retrieve account metadata
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this account.
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: sample account metadata
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - accounts
      x-accepts: application/json
  /api/accounts/{id}/balances/:
    get:
      description: |-
        Access account balances.

        Balances will be returned in Berlin Group PSD2 format.
      operationId: retrieve account balances
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this account.
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: sample account balances
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - accounts
      x-accepts: application/json
  /api/accounts/{id}/details/:
    get:
      description: |-
        Access account details.

        Account details will be returned in Berlin Group PSD2 format.
      operationId: retrieve account details
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this account.
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: sample account details
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - accounts
      x-accepts: application/json
  /api/accounts/{id}/transactions/:
    get:
      description: |-
        Access account transactions.

        Transactions will be returned in Berlin Group PSD2 format.
      operationId: retrieve account transactions
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this account.
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: sample transaction data
        "409":
          description: Account state does not support this operation
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - accounts
      x-accepts: application/json
  /api/agreements/enduser/:
    get:
      description: API endpoints related to end-user agreements.
      operationId: retrieve all EUAs for an end user
      parameters:
      - description: Your enduser ID, used for filtering results.
        explode: true
        in: query
        name: enduser_id
        required: true
        schema:
          type: string
        style: form
      - description: Number of results to return per page.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: The initial index from which to return the results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedEndUserAgreementList'
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - agreements
      x-accepts: application/json
    post:
      description: API endpoints related to end-user agreements.
      operationId: create EUA
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndUserAgreement'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EndUserAgreement'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EndUserAgreement'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndUserAgreement'
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - agreements
      x-contentType: application/json
      x-accepts: application/json
  /api/agreements/enduser/{id}/:
    delete:
      description: Delete End User Agreement.
      operationId: delete EUA by id
      parameters:
      - description: A UUID string identifying this end user agreement.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: No response body
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - agreements
      x-accepts: application/json
    get:
      description: API endpoints related to end-user agreements.
      operationId: retrieve EUA by id
      parameters:
      - description: A UUID string identifying this end user agreement.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndUserAgreement'
          description: EUA
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - agreements
      x-accepts: application/json
  /api/agreements/enduser/{id}/accept/:
    put:
      description: Accept an end-user agreement via the API.
      operationId: accept EUA
      parameters:
      - description: A UUID string identifying this end user agreement.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnduserAcceptanceDetails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EnduserAcceptanceDetails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EnduserAcceptanceDetails'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndUserAgreement'
          description: EUA
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - agreements
      x-contentType: application/json
      x-accepts: application/json
  /api/agreements/enduser/{id}/text/:
    get:
      description: Show the text of the end-user agreement.
      operationId: retrieve EUA text
      parameters:
      - description: A UUID string identifying this end user agreement.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: EUA Text
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - agreements
      x-accepts: application/json
  /api/aspsps/:
    get:
      description: List all ASPSPs available.
      operationId: retrieve all supported ASPSP(s) in a given country
      parameters:
      - description: ISO 3166 two-character country code
        examples:
          Germany:
            description: ISO 3166 two-character code for Germany
            summary: Germany
            value: DE
          UnitedKingdom:
            description: ISO 3166 two-character code for the UK
            summary: United Kingdom
            value: GB
        explode: true
        in: query
        name: country
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                SomeOfSupportedASPSPs:
                  summary: some of supported ASPSPs
                  value:
                  - id: N26_NTSBDEB1
                    name: N26 Bank
                    bic: NTSBDEB1
                    transaction_total_days: "90"
                    countries:
                    - "NO"
                    - DE
                    - '...'
                    - AT
                    logo: https://cdn.nordigen.com/ais/N26_SANDBOX_NTSBDEB1.png
                  - id: ABNAMRO_FTSBDEFAXXX
                    name: ABN AMRO Bank Commercial
                    bic: FTSBDEFAXXX
                    transaction_total_days: "558"
                    countries:
                    - DE
                    logo: https://cdn.nordigen.com/ais/ABNAMRO_FTSBDEFAXXX.png
              schema:
                items:
                  $ref: '#/components/schemas/Aspsp'
                type: array
          description: list of supported ASPSPs in the country
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - aspsps
      x-accepts: application/json
  /api/aspsps/{id}/:
    get:
      description: Get details about a specific ASPSP.
      operationId: retrieve details about specific ASPSP
      parameters:
      - examples:
          N26:
            description: Nordigen's ASPSP ID for N26
            summary: N26
            value: N26_NTSBDEB1
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                N26Bank:
                  description: N26 Bank
                  summary: N26 Bank
                  value:
                    id: N26_NTSBDEB1
                    name: N26 Bank
                    bic: NTSBDEB1
                    transaction_total_days: "90"
                    countries:
                    - "NO"
                    - DE
                    - '...'
                    - AT
                    logo: https://cdn.nordigen.com/ais/N26_SANDBOX_NTSBDEB1.png
                ABNAMROBank:
                  description: ABN AMRO Bank
                  summary: ABN AMRO Bank
                  value:
                    id: ABNAMRO_FTSBDEFAXXX
                    name: ABN AMRO Bank Commercial
                    bic: FTSBDEFAXXX
                    transaction_total_days: "558"
                    countries:
                    - DE
                    logo: https://cdn.nordigen.com/ais/ABNAMRO_FTSBDEFAXXX.png
              schema:
                $ref: '#/components/schemas/Aspsp'
          description: ASPSP Representation
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - aspsps
      x-accepts: application/json
  /api/requisitions/:
    get:
      description: API endpoints related to requisitions.
      operationId: retrieve all requisitions
      parameters:
      - description: Number of results to return per page.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: The initial index from which to return the results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRequisitionList'
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - requisitions
      x-accepts: application/json
    post:
      description: API endpoints related to requisitions.
      operationId: create a new requisition
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Requisition'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Requisition'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Requisition'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Requisition'
          description: requisition
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - requisitions
      x-contentType: application/json
      x-accepts: application/json
  /api/requisitions/{id}/:
    delete:
      description: Delete Requisition and all End User Agreements.
      operationId: delete requisition
      parameters:
      - description: A UUID string identifying this requisition.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: No response body
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - requisitions
      x-accepts: application/json
    get:
      description: API endpoints related to requisitions.
      operationId: requisition by id
      parameters:
      - description: A UUID string identifying this requisition.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Requisition'
          description: requisition
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - requisitions
      x-accepts: application/json
  /api/requisitions/{id}/links/:
    post:
      description: Get links for user redirection.
      operationId: create ASPSP authorization link
      parameters:
      - description: A UUID string identifying this requisition.
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequisitionLinkParams'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RequisitionLinkParams'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RequisitionLinkParams'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequisitionLinks'
          description: link to initiate authorization with ASPSP
      security:
      - tokenAuth: []
      - cookieAuth: []
      tags:
      - requisitions
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    Account:
      description: The representation of a bank account.
      example:
        last_accessed: 2000-01-23T04:56:07.000+00:00
        aspsp_identifier: aspsp_identifier
        created: 2000-01-23T04:56:07.000+00:00
        iban: iban
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        status: ""
      properties:
        id:
          description: The ID of this Account, used to refer to this account in other
            API calls.
          format: uuid
          readOnly: true
          title: Account ID
          type: string
        created:
          description: The date & time at which the account object was created.
          format: date-time
          readOnly: true
          title: Created date/time
          type: string
        last_accessed:
          description: The date & time at which the account object was last accessed.
          format: date-time
          nullable: true
          readOnly: true
          title: Last accessed date/time
          type: string
        iban:
          description: The Account IBAN
          readOnly: true
          type: string
        aspsp_identifier:
          description: The ASPSP associated with this account.
          readOnly: true
          title: ASPSP ID
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/AccountStatusEnum'
          description: The processing status of this account.
          readOnly: true
          title: Account Status
      required:
      - aspsp_identifier
      - created
      - iban
      - id
      - last_accessed
      - status
      type: object
    AccountStatusEnum:
      enum:
      - DISCOVERED
      - PROCESSING
      - READY
      - ERROR
      - SUSPENDED
      type: string
    Aspsp:
      description: Represents an ASPSP.
      example:
        transaction_total_days: "90"
        name: name
        logo: logo
        id: id
        countries:
        - countries
        - countries
        bic: bic
      properties:
        id:
          type: string
        name:
          type: string
        bic:
          type: string
        transaction_total_days:
          default: "90"
          type: string
        countries:
          items:
            type: string
          type: array
        logo:
          type: string
      required:
      - countries
      - id
      - logo
      - name
      type: object
    EndUserAgreement:
      description: Represents an end-user agreement.
      example:
        access_scope:
        - access_scope
        - access_scope
        enduser_id: enduser_id
        created: 2000-01-23T04:56:07.000+00:00
        accepted: 2000-01-23T04:56:07.000+00:00
        aspsp_id: aspsp_id
        access_valid_for_days: 441289069
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        max_historical_days: -1803530559
      properties:
        id:
          description: The ID of this End User Agreement, used to refer to this end
            user agreement in other API calls.
          format: uuid
          readOnly: true
          title: End User Agreement ID
          type: string
        created:
          description: The date & time at which the end user agreement was created.
          format: date-time
          readOnly: true
          title: Created Date
          type: string
        max_historical_days:
          default: 90
          description: Maximum number of days of transaction data to retrieve.
          maximum: 2147483647
          minimum: -2147483648
          title: Maximum Historical Days
          type: integer
        access_valid_for_days:
          default: 90
          description: Number of days from acceptance that the access can be used.
          maximum: 2147483647
          minimum: -2147483648
          readOnly: true
          title: Access Valid For (Days)
          type: integer
        access_scope:
          default:
          - balances
          - details
          - transactions
          description: Array containing one or several values of ['balances', 'details',
            'transactions']
          items:
            title: Level of information to access (by default all)
            type: string
          title: Level of information to access (by default all)
          type: array
        accepted:
          description: The date & time at which the end user accepted the agreement.
          format: date-time
          nullable: true
          readOnly: true
          title: Accepted Date
          type: string
        enduser_id:
          description: A unique ID that identifies this user in your system. For data
            protection purposes, it must be possible to identify your users using
            this value. Data protection related requests may quote this value to identify
            data subjects.
          maxLength: 256
          nullable: true
          title: End User ID
          type: string
        aspsp_id:
          description: an ASPSP ID for this EUA
          type: string
      required:
      - accepted
      - access_valid_for_days
      - aspsp_id
      - created
      - enduser_id
      - id
      type: object
    EnduserAcceptanceDetails:
      description: Represents end-user details.
      example:
        ip_address: ip_address
        user_agent: user_agent
      properties:
        user_agent:
          title: user agent string for the end user
          type: string
        ip_address:
          title: end user IP address
          type: string
      required:
      - ip_address
      - user_agent
      type: object
    PaginatedEndUserAgreementList:
      example:
        next: http://api.example.org/accounts/?offset=400&limit=100
        previous: http://api.example.org/accounts/?offset=200&limit=100
        count: 123
        results:
        - access_scope:
          - access_scope
          - access_scope
          enduser_id: enduser_id
          created: 2000-01-23T04:56:07.000+00:00
          accepted: 2000-01-23T04:56:07.000+00:00
          aspsp_id: aspsp_id
          access_valid_for_days: 441289069
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          max_historical_days: -1803530559
        - access_scope:
          - access_scope
          - access_scope
          enduser_id: enduser_id
          created: 2000-01-23T04:56:07.000+00:00
          accepted: 2000-01-23T04:56:07.000+00:00
          aspsp_id: aspsp_id
          access_valid_for_days: 441289069
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          max_historical_days: -1803530559
      properties:
        count:
          example: 123
          type: integer
        next:
          example: http://api.example.org/accounts/?offset=400&limit=100
          format: uri
          nullable: true
          type: string
        previous:
          example: http://api.example.org/accounts/?offset=200&limit=100
          format: uri
          nullable: true
          type: string
        results:
          items:
            $ref: '#/components/schemas/EndUserAgreement'
          type: array
      type: object
    PaginatedRequisitionList:
      example:
        next: http://api.example.org/accounts/?offset=400&limit=100
        previous: http://api.example.org/accounts/?offset=200&limit=100
        count: 123
        results:
        - redirect: https://openapi-generator.tech
          reference: reference
          enduser_id: enduser_id
          created: 2000-01-23T04:56:07.000+00:00
          agreements:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          user_language: user_language
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          accounts:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          status: ""
        - redirect: https://openapi-generator.tech
          reference: reference
          enduser_id: enduser_id
          created: 2000-01-23T04:56:07.000+00:00
          agreements:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          user_language: user_language
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          accounts:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          status: ""
      properties:
        count:
          example: 123
          type: integer
        next:
          example: http://api.example.org/accounts/?offset=400&limit=100
          format: uri
          nullable: true
          type: string
        previous:
          example: http://api.example.org/accounts/?offset=200&limit=100
          format: uri
          nullable: true
          type: string
        results:
          items:
            $ref: '#/components/schemas/Requisition'
          type: array
      type: object
    Requisition:
      description: RequisitionSerializer.
      example:
        redirect: https://openapi-generator.tech
        reference: reference
        enduser_id: enduser_id
        created: 2000-01-23T04:56:07.000+00:00
        agreements:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        user_language: user_language
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        accounts:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        status: ""
      properties:
        id:
          format: uuid
          readOnly: true
          type: string
        created:
          description: The date & time at which the requisition was created.
          format: date-time
          nullable: true
          readOnly: true
          title: Created Date
          type: string
        redirect:
          description: redirect URL to your application after end-user authorization
            with ASPSP
          format: uri
          nullable: true
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/RequisitionStatusEnum'
          description: status of this requisition
          readOnly: true
        agreements:
          description: array of EUAs associated with this requisition
          items:
            format: uuid
            title: agreements
            type: string
          type: array
        accounts:
          description: array of account IDs retrieved within a scope of this requisition
          items:
            format: uuid
            title: accounts
            type: string
          readOnly: true
          type: array
        reference:
          description: additional ID to identify the end user
          maxLength: 256
          type: string
        enduser_id:
          description: end-user id in client's system, usually a UUID
          maxLength: 256
          title: end user id
          type: string
        user_language:
          description: user language for the views
          maxLength: 5
          type: string
      required:
      - accounts
      - created
      - enduser_id
      - id
      - redirect
      - reference
      - status
      type: object
    RequisitionLinkParams:
      description: RequisitionLinkParamsSerializer.
      example:
        aspsp_id: aspsp_id
      properties:
        aspsp_id:
          description: ASPSP ID. Should match one used while creating EUA, if it's
            linked to this requisition
          type: string
      required:
      - aspsp_id
      type: object
    RequisitionLinks:
      description: RequisitionLinksSerializer.
      example:
        initiate: https://openapi-generator.tech
      properties:
        initiate:
          format: uri
          readOnly: true
          type: string
      required:
      - initiate
      type: object
    RequisitionStatusEnum:
      enum:
      - CR
      - ID
      - LN
      - RJ
      - ER
      - SU
      - EX
      type: string
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
    cookieAuth:
      in: cookie
      name: Session
      type: apiKey
    tokenAuth:
      description: Token-based authentication with required prefix "Token"
      in: header
      name: Authorization
      type: apiKey

